//! The opcode table in `docs/bytecode.md`, generated from the layout `ruta-bytecode` defines
//! so that the document cannot drift away from the code.

use std::collections::HashMap;
use std::fs;

use anyhow::{Context, Result, anyhow, bail};
use ruta_bytecode::{OpCode, Operand, decode, instruction_len};

use crate::repo_root;

const DOC: &str = "docs/bytecode.md";
const SOURCE: &str = "crates/ruta-bytecode/src/op.rs";
const BEGIN: &str = "<!-- opcode table: generated by `cargo xtask bytecode-table` -->";
const END: &str = "<!-- end of opcode table -->";

/// Rewrites the table between its markers. With `check`, only fails if that would change it.
pub(crate) fn table(check: bool) -> Result<()> {
    let root = repo_root();
    let path = root.join(DOC);
    let doc = fs::read_to_string(&path).with_context(|| format!("cannot read {DOC}"))?;
    let source =
        fs::read_to_string(root.join(SOURCE)).with_context(|| format!("cannot read {SOURCE}"))?;

    let (head, rest) = doc
        .split_once(BEGIN)
        .with_context(|| format!("{DOC} has no `{BEGIN}`"))?;
    let (_, tail) = rest
        .split_once(END)
        .with_context(|| format!("{DOC} has no `{END}`"))?;
    let fresh = format!("{head}{BEGIN}\n{}{END}{tail}", render(&meanings(&source))?);

    if check {
        if fresh != doc {
            bail!("{DOC} is out of date - run `cargo xtask bytecode-table`");
        }

        return Ok(());
    }

    fs::write(&path, fresh).with_context(|| format!("cannot write {DOC}"))
}

fn render(meanings: &HashMap<String, String>) -> Result<String> {
    let mut out = String::from(
        "\n| Byte | Mnemonic | Operands | Length | Meaning |\n| ---: | --- | --- | ---: | --- |\n",
    );

    for byte in 0..=u8::MAX {
        let Some(opcode) = OpCode::from_byte(byte) else {
            continue;
        };

        let (variant, names) = names(byte, opcode.operands())?;
        let operands = names
            .iter()
            .zip(opcode.operands())
            .map(|(name, operand)| format!("`{name}` {}", width(*operand)))
            .collect::<Vec<_>>()
            .join(", ");
        let length = instruction_len(byte).context("a known opcode has a length")?;
        let meaning = meanings.get(&variant).map_or("", String::as_str);

        out.push_str(&format!(
            "| {byte} | `{opcode:?}` | {operands} | {length} | {meaning} |\n"
        ));
    }

    out.push('\n');

    Ok(out)
}

/// The decoded instruction's variant, and its operands' names in the order they are written.
/// Each operand is given a different value, and the field that value lands in is its name.
fn names(byte: u8, operands: &[Operand]) -> Result<(String, Vec<String>)> {
    let mut code = vec![byte];

    for (at, operand) in operands.iter().enumerate() {
        let value = at as u32 + 1;
        code.extend_from_slice(&value.to_le_bytes()[..operand.width() as usize]);
    }

    let (op, _) = decode(&code, 0).map_err(|error| anyhow!("{error:?}"))?;
    let text = format!("{op:?}");
    let (variant, fields) = text
        .split_once(" { ")
        .with_context(|| format!("`{text}` has no fields"))?;
    let fields: Vec<(&str, &str)> = fields
        .trim_end_matches(" }")
        .split(", ")
        .filter_map(|field| field.split_once(": "))
        .collect();

    let names = (1..=operands.len())
        .map(|value| {
            let value = value.to_string();

            fields
                .iter()
                .find(|(_, held)| *held == value)
                .map(|(name, _)| (*name).to_owned())
                .with_context(|| format!("no field of `{text}` holds {value}"))
        })
        .collect::<Result<_>>()?;

    Ok((variant.to_owned(), names))
}

/// Each `Op` variant's doc comment, keyed by variant.
fn meanings(source: &str) -> HashMap<String, String> {
    let mut out = HashMap::new();

    let Some((_, body)) = source.split_once("pub enum Op {") else {
        return out;
    };

    let mut doc: Vec<&str> = Vec::new();

    for line in body.lines() {
        let line = line.trim();

        if line == "}" {
            break;
        }

        if let Some(text) = line.strip_prefix("///") {
            doc.push(text.trim());
            continue;
        }

        if let Some(name) = line.strip_suffix(" {")
            && name.chars().all(char::is_alphanumeric)
            && !doc.is_empty()
        {
            out.insert(name.to_owned(), tidy(&doc.join(" ")));
        }

        doc.clear();
    }

    out
}

/// Rustdoc links become plain code spans, and a `|` would end the table cell.
fn tidy(text: &str) -> String {
    text.replace("[`Op::", "`")
        .replace("[`", "`")
        .replace("`]", "`")
        .replace('|', "\\|")
}

fn width(operand: Operand) -> &'static str {
    match operand {
        Operand::U8 => "u8",
        Operand::U16 => "u16",
        Operand::U32 => "u32",
        Operand::I32 => "i32",
    }
}
